---

- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install jenkins prerequisite apt packages
  apt:
    name:  "{{ item }}"
    state: present
  with_items: "{{ jenkins_prereq_pkgs|union(jenkins_apt_pkgs_extra) }}"
  when: ansible_os_family|lower == 'debian'

- name: Install jenkins prerequisite yum packages
  yum:
    name:  "{{ item }}"
    state: present
  with_items: "{{ jenkins_prereq_pkgs|union(jenkins_yum_pkgs_extra) }}"
  when: ansible_os_family|lower == 'redhat'

- name: Install extra pip packages desired
  pip:
    name:  "{{ item }}"
    state: present
  with_items: "{{ jenkins_pip_pkgs_extra }}"

- name: Jenkins Install
  include: "{{ jenkins_role|default('master') }}.yml"

- name: Jenkins CLI
  include: cli.yml
  when: jenkins_role == 'master'

- name: UI users
  include: users.yml
  when: jenkins_role == 'master'
